FROM python:3.7
ENV PYTHONUNBUFFERED 1

ARG GIT_USER
ARG GIT_BRANCH

RUN mkdir /zds
WORKDIR /zds

ENV DOCKERIZE_VERSION v0.6.1
RUN wget -q https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

RUN wget -q https://github.com/${GIT_USER}/zds-site/archive/${GIT_BRANCH}.tar.gz -O deploy.tar.gz
RUN tar -xf deploy.tar.gz
RUN cp -rp zds-site-`echo ${GIT_BRANCH} | sed -r 's/\//-/g' | sed -r 's/^v//g'`/* .
RUN rm -rf deploy.tar.gz
RUN rm -rf zds-site-`echo ${GIT_BRANCH} | sed -r 's/\//-/g' | sed -r 's/^v//g'`

COPY ./settings_docker.py /zds/zds/settings/docker.py
COPY ./service/zds-index.sh /zds/zds-index.sh

RUN pip3 -q install -r /zds/requirements-dev.txt
RUN pip3 -q install -r /zds/requirements-prod.txt
